#ifndef __MyProject3MyFrame1__
#define __MyProject3MyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "funcsGUI.h"

//// end generated include

/** Implementing MyFrame1 */
class MyProject3MyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void m_button1Click( wxCommandEvent& event );
		void m_button1KeyDown( wxKeyEvent& event );
	public:
		/** Constructor */
		MyProject3MyFrame1( wxWindow* parent );
	//// end generated class members




};

#endif // __MyProject3MyFrame1__
